# Generated by Django 4.2.30 on 2026-08-24 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LSA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("learning_difficulty_confirmed", models.BooleanField()),
                ("parent_consent_signed", models.BooleanField()),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("school_grade", models.PositiveSmallIntegerField()),
                ("iep_document_attached", models.BooleanField(default=False)),
                (
                    "dcyn_clearance_status",
                    models.CharField(
                        choices=[("CLEARED", "Cleared"), ("BLOCKED", "Blocked")],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_lsa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="onboarding.lsa",
                    ),
                ),
            ],
            options={
                "db_table": "student_onboarding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATED", "Created"), ("UPDATED", "Updated")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("dcyn_clearance_status", models.CharField(max_length=10)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.studentonboarding",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="studentonboarding",
            index=models.Index(
                fields=["assigned_lsa"], name="student_onb_assigne_3ebd9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentonboarding",
            index=models.Index(
                fields=["dcyn_clearance_status"], name="student_onb_dcyn_cl_004452_idx"
            ),
        ),
    ]
